# Generated by Django 5.1.1 on 2025-02-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='VuSRD2hpAByda6uJFgtSdKs1Su6qvtu3', editable=False, max_length=32, unique=True),
        ),
    ]
